### ISSUE TITLE
Add images for the two new ecosystem cards

### ISSUE THREAD

**Issue by daveaneo** [Blockchain-Solutions-LLC/quarrychain-landing#22]
![swap](https://user-images.githubusercontent.com/54771105/203397874-ad44099b-ecea-480e-a851-d6f1f772971e.png)
![gold](https://user-images.githubusercontent.com/54771105/203397876-9dbb72c8-fdda-4c7b-9bc3-bf548a47a9a0.png)

" for the QuarrySwap tab, use the blue arrow logo and for the Tokenizing Real World Assets tab, use the Commodities logo"

**Comment by ArrambideTechnologies** [comment]
Hey David, so what I meant by the "QuarrySwap Tab" and the "Tokenized Real World Assets" tab was those small summary slide boxes that you see on the homepage. I just wanted you to edit the Moai And Tuff and replace them with the new descriptions/logos. However, I did realize that I did not specify to create a separate page for QuarrySwap and Tokenzied Real World Assets. If that would take too long, then I think for now it's fine we just edit the homepage slide tabs and then later create separate pages for QuarrySwap and QuarryChains Digital Real World Marketplace.
